# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: Graphite
    orgId: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    secureJsonData:
      token: token
    jsonData:
      version: Flux
      organization: influxdata-org
      defaultBucket: test
      tlsSkipVerify: true
