{
 "title": "Room's data",
 "time": { "from": "now-1y/y", "to": "now-1y/y" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "RoomID",
    "label": "RoomID",
    "query": "SELECT DISTINCT room_id FROM entity_model_room\nUNION\nSELECT DISTINCT room_id FROM entity_model_room_flags"
   },
   {
    "name": "topicNum",
    "label": "Topic number",
    "query": "SELECT topic_num FROM entity_model_room"
   }
  ]
 },
 "panels": [
  {
   "title": "Topic keywords",
   "type": "magnesium-wordcloud-panel",
   "gridPos": { "h": 12, "w": 17, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT word, weight FROM entity_model_room WHERE room_id = '$RoomID' AND topic_num = $topicNum ORDER BY weight DESC"
    }
   ]
  },
  {
   "title": "Num of detected violence",
   "type": "stat",
   "gridPos": { "h": 12, "w": 7, "x": 17, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT SUM(sexual + hate + violence + self_harm + sexual_minors + hate_threatening + violence_graphic) AS total_sum FROM entity_model_room_flags WHERE room_id = '$RoomID' "
    }
   ]
  },
  {
   "title": "Violence categories",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT sexual, hate, violence, self_harm, sexual_minors, hate_threatening, violence_graphic FROM entity_model_room_flags WHERE room_id = '$RoomID' "
    }
   ]
  }
 ]
}